// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2hoEgxZhQ8QOTEl1y1eBpxfoZAAzvgk',
    appId: '1:857348842396:web:d09df8826bdd0658b4de59',
    messagingSenderId: '857348842396',
    projectId: 'contract-fitness',
    authDomain: 'contract-fitness.firebaseapp.com',
    storageBucket: 'contract-fitness.firebasestorage.app',
    measurementId: 'G-TFT14QBBF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2rPW_uu6zY9FWlKLMfO22c7KvTHp8Y-I',
    appId: '1:857348842396:android:bd2c7e1c60a9afe8b4de59',
    messagingSenderId: '857348842396',
    projectId: 'contract-fitness',
    storageBucket: 'contract-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-XPyjmfks8ceOWnAP-nRjmFG1aDImK0Y',
    appId: '1:857348842396:ios:69f4ea1479afb8fbb4de59',
    messagingSenderId: '857348842396',
    projectId: 'contract-fitness',
    storageBucket: 'contract-fitness.firebasestorage.app',
    iosBundleId: 'com.example.contractfitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-XPyjmfks8ceOWnAP-nRjmFG1aDImK0Y',
    appId: '1:857348842396:ios:69f4ea1479afb8fbb4de59',
    messagingSenderId: '857348842396',
    projectId: 'contract-fitness',
    storageBucket: 'contract-fitness.firebasestorage.app',
    iosBundleId: 'com.example.contractfitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt2hoEgxZhQ8QOTEl1y1eBpxfoZAAzvgk',
    appId: '1:857348842396:web:8fb3d4a4222e6701b4de59',
    messagingSenderId: '857348842396',
    projectId: 'contract-fitness',
    authDomain: 'contract-fitness.firebaseapp.com',
    storageBucket: 'contract-fitness.firebasestorage.app',
    measurementId: 'G-WMXSCTL0PF',
  );
}
